### ISSUE TITLE
dhcp server stops working when mesh_fastd is restarted

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible-configs#1]
Since we are not using the a bridge around the ```bat0``` interface, the dhcp server seems to stop working when sombody restarts the mesh interface of fastd.

For now the fix is to restart the dhcp server as well after restarting the fastd instance.
```
systemctl restart fastd@mesh_fastd
systemctl restart isc-dhcp-server
```

But to fix this over all, we should investigate this.

**Comment by lemoer** [comment]
This caused some issues in the boot process with networkd. The ```eth0``` device is not raised correctly on on the boot

@1977er Is using systemd backports the solution for this problem?

**Comment by 1977er** [comment]
On Debian Jessie with systemd 215 the `eth0` device does not come up anymore. Using systemd 230 from Jessie backports solves this issue.

**Comment by lemoer** [comment]
It seems fixed.
