### ISSUE TITLE
Create vars/all_sn.yml to reduce redundancy

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible-configs#14]
There are a lot of variables, that are shared between all supernodes. We should outsource them into an own file ```vars/all_sn.yml```

**Comment by lemoer** [comment]
```
- dns_recursive_allowed_private_rdns_zones:
  - "8.0.0.0.e.e.f.f.a.c.d.f.ip6.arpa."
```

from ```vars/all_hosts.yml``` should be migrated to there as well.

**Comment by lemoer** [comment]
Maybe we could use another level of abstaction with *include*:

**supernode.yml:**
``` yml
---

- hosts: sn01
  tasks:
  - name: foo und bar
    set_fact:
      a:
        c: ['foo', 'bar']

  - name: print
    debug: var=a

  - include: add_it.yml b="hey"

  - include: add_it.yml b="hey"

  - name: print
    debug: var=a
```

**add_it.yml:**
```
--- yml
- name: add it
  set_fact:
    a: "{{ a|combine({ \"c\": a[\"c\"] + [b] }) }}"
```
This include snippet adds variable b into array in a["c"].

**Comment by 1977er** [comment]
Can you add a tangible example please? ;-)

**Comment by 1977er** [comment]
And everybody is complaining about Perl regexes.
