### ISSUE TITLE
Multiple fastd instances on multi-core supernodes

### ISSUE THREAD

**Issue by lemoer** [freifunkh/ansible-configs#24]
The following supernodes have multiple cores:
- sn09 (4 cores)
- sn08 (2 cores)
- sn07 (2 cores)
- sn05 (2 cores)
- sn04 (4 cores)
- sn02 (2 cores)

The following only have one core:
- sn01 (1 core)

**Comment by cawi2001** [comment]
This can be done on Hostway Server only ... why? Because of Traffic limitation on Hetzner and Netcup Server. On Hetzner Server we are quite reaching 30 TB. On Netcup Server we have the Limit of 80 MBit/sec.

**Comment by 1977er** [comment]
Upcoming netsplit forces us to use multiple instances of fastd. Closing.

**Comment by AiyionPrime** [comment]
just to keep this in mind, we should measure sometime in the future, whether the myth, that fastd would perform better - even on single cores - if started with multiple instances.

**Comment by lemoer** [comment]
never heard about that myth?

**Comment by AiyionPrime** [comment]
freifunk harz? Claimed it to be true. But as other things revealed to be wrong before, it's a myth till now.
He mentioned something like he'd tested it.
