### ISSUE TITLE
Add Exit Nodes as separated statistic to Grafana in stats.ffh.zone

### ISSUE THREAD

**Issue by cawi2001** [freifunkh/ansible-configs#25]
Until now, It's not clear to see the difference between one exit-node and the actual three exit-nodes.
I really see no difference in bandwith behavier comparing today and two months ago where we had half of the actual infrastructure.

**Comment by 1977er** [comment]
@cawi2001 The magic word is: SPOF.

**Comment by cawi2001** [comment]
It's not SPOF only. If it would SPOF then we didn't had problems with Netcup Exit-Node with 80 MBit/sec, because other Exit-Nodes are well running. We want to fasten the Network, because one year before, a WDR4900 could reach 30-40 MBit/sec ... today it's more or less 15 - 25 MBit/sec.
So it's for performance and I like to see it in our statistics.  :-)

**Comment by 1977er** [comment]
https://stats.ffh.zone/dashboard/db/exitnodes-ubersicht?orgId=1
