### ISSUE TITLE
babeld/routing: losing default route in table 42

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible-configs#38]
Irgendwelche unbekannten Ereignisse lassen den Kernel die default Route in der freifunk Tabelle (42) vergessen. Ein Abstubsen des Babel Dienstes löst das Problem.

- [ ] Herausfinden, was das verursacht

Aktueller Workaround auf sn02: babeld alle 5min neustarten.

**Comment by lemoer** [comment]
- What does the status socket of babeld say to this issue? (`echo dump | nc ::1 33123`)
- Is only the default route affected?

**Comment by 1977er** [comment]
- Turns out: ferm was not enabled on boot. 
- Turns out: ansibles babeld role is not able to enable ferm (had to manually enable it)
- Turns out: babeld is deaf when the firewall is up, altough -A INPUT -s fe80::/64 -p udp -m udp --dport 6696 -j ACCEPT is set.

And now?

**Comment by lemoer** [comment]
```-A INPUT -s fe80::/64 -p udp -m udp --dport 6696 -j ACCEPT``` seems to work on sn08 (no ferm).

What happens if babeld gets restarted?

**Comment by lemoer** [comment]
You missed to add rules to allow the gre traffic from and to aegiedientor. Not babeld related.

**Comment by 1977er** [comment]
Marvelous. How did you spot that?

**Comment by lemoer** [comment]
Ping over the gre interface also did not work.

**Comment by 1977er** [comment]
It still does not.

**Comment by lemoer** [comment]
*is not working until gre packets are allowed from aegidientor
